### ISSUE TITLE
C Headers missing definitions. 

### ISSUE THREAD

**Issue by theclashingfritz** [loblao/libotp-nametags#6]
The headers are missing definitions for three structures. The three structures are vtable_generic_typed, vtable_generic_refcount, and __string.

**Comment by loblao** [comment]
`vtable_generic_refcount` and `vtable_generic_typed` are in [putil.h](https://github.com/loblao/libotp-nametags/tree/master/c_headers/panda3d-1.7.1/putil.h) and `__string` can now be found [here](https://github.com/loblao/libotp-nametags/tree/master/c_headers/string.h).

**Comment by theclashingfritz** [comment]
Thanks.
