### ISSUE TITLE
Issue with ChatBalloon..

### ISSUE THREAD

**Issue by rasheelprogrammer** [loblao/libotp-nametags#7]
I know this might be a Panda3D-related crash but i have tried everything...

File "libotp\ChatBalloon.py", line 61, in scan_balloon
    self.m_copy_node = node.copySubgraph()
AttributeError: 'panda3d.core.NodePath' object has no attribute 'copySubgraph'
Press any key to continue . . .

**Comment by pythonengineer** [comment]
You need a subgraph to copy.

**Comment by loblao** [comment]
ChatBalloon takes a PandaNode argument but you're giving it a NodePath.

**Comment by rasheelprogrammer** [comment]
Got it. Thank you.
